test: validate new percy token in CI with FIXED auth check

diff --git a/.github/workflows/uvt.yml b/.github/workflows/uvt.yml
--- a/.github/workflows/uvt.yml
+++ b/.github/workflows/uvt.yml
@@ -58,18 +58,18 @@ jobs:
               exit 1
             }
           fi
-        - name: Validate Percy Authentication
-          run: |
-            if [ -n "\\${{ secrets.PERCY_TOKEN }}" ]; then
-              npx percy exec -- echo "Percy Authentication Successful" || {
-                echo "Percy authentication failed! Check your PERCY_TOKEN."
-                exit 1
-              }
-            else
-              echo "No PERCY_TOKEN provided, skipping auth check."
-            fi
-          env:
-            PERCY_TOKEN: \\${{ secrets.PERCY_TOKEN }}
+      - name: Validate Percy Authentication
+        run: |
+          if [ -n "\\${{ secrets.PERCY_TOKEN }}" ]; then
+            npx percy exec -- echo "Percy Authentication Successful" || {
+              echo "Percy authentication failed! Check your PERCY_TOKEN."
+              exit 1
+            }
+          else
+            echo "No PERCY_TOKEN provided, skipping auth check."
+          fi
+        env:
+          PERCY_TOKEN: \\${{ secrets.PERCY_TOKEN }}
 
       - name: Cache Playwright Browsers
         id: playwright-cache
